stages:
  get-data:
    cmd: python '.calkit/notebook-stages/get-data/script.py'
    deps:
    - .calkit/notebook-stages/get-data/script.py
    outs:
    - .calkit/notebook-stages/get-data/outs/df.parquet
  plot:
    cmd: python '.calkit/notebook-stages/plot/script.py'
    deps:
    - .calkit/notebook-stages/get-data/outs/df.parquet
    - .calkit/notebook-stages/plot/script.py
    outs:
    - .calkit/notebook-stages/plot/outs/fig.pickle
    - figures/plot.png
  notebook-to-html:
    cmd: calkit nb execute --to html notebook.ipynb
    deps:
    - notebook.ipynb
    outs:
    - .calkit/notebooks/html/notebook.html
    meta:
      calkit:
        type: notebook
        path: notebook.ipynb
        title: Pipeline notebook
        description: This notebook is also a DVC pipeline.
