# This script was automatically generated by Calkit

import calkit

df = calkit.load_notebook_stage_out(stage_name='get-data', out_name='df', fmt='parquet', engine='pandas')


import os

os.makedirs("figures", exist_ok=True)

fig = df.plot(backend="plotly")
fig.write_image("figures/plot.png")
fig
calkit.save_notebook_stage_out(fig, stage_name='plot', out_name='fig')
