# This script was automatically generated by Calkit

import calkit


import pandas as pd
import time

# Let's pretend this is an expensive call
time.sleep(10)

df = pd.DataFrame({"col1": range(1000)})
df.describe()
calkit.save_notebook_stage_out(df, stage_name='get-data', out_name='df', fmt='parquet', engine='pandas')
